import { RFValue } from "react-native-responsive-fontsize";

export default {
  colors: {
    primary: "#00349a",
    secondary: "#000",
    background_global: "#f1f1f1",
    off: "#ff0000",
    on: "#2e7d32",
    button_text_disabled: "#a09e9e",
    background_opacity: "#2B2B28",
    input_placeholder: "#a09e9e",
    button_terms_of_use: "#3d3d3d",
    pdf_color: "#BF6363",

    background_black_opacity: "rgba(0,0,0,0.5)",

    background_dark: "#070A1A",
    background_dark_blue: "#000046",
    white: "#fff",
    white_light: "#eee",
    background_white: "#f8f9fa",
    background_white_light: "#f0f0f0",
    text_gray: "#666",
    icon_gray: "#444",
    black: "#000",
    // NÃO REMOVER NEM ALTERAR  background_black_light, POIS É A COR DE BACKGROUND DO MODAL
    background_black_light: "rgba(0,0,0,0.25)",
    placeholder: "#615f66",
    grayLight: "#999",
    border: "#ddd",
    border_white_light: "#f5f5f5",
    border_green: "#2e7d32",
    background_greenLight: "#D5E6C9",
    red: "#E83F5B",
    redLight: "#F8E3E1",
    orange: "#eb4034",
    yellowStrong: "#f8a63d",
    yellowLight: "#f1d6a9",
    background_blue_light: "#367FAE",
  },
  toast: {
    secondary_light: "#ff872c4d",
    success: "#12A454",
    success_light: "#12a45480",
    attention: "#E83F5B",
    attention_light: "#e83f5b80",
  },
  fonts: {
    thin: "Roboto_100Thin",
    regular: "Roboto_400Regular",
    regular_italic: "Roboto_400Regular_Italic",
    medium: "Roboto_500Medium",
    bold: "Roboto_700Bold",
    black: "Roboto_900Black",

    secondary_regular: "Lato_400Regular",
    secondary_regular_Italic: "Lato_400Regular_Italic",
    secondary_bold: "Lato_700Bold",
    secondary_black: "Lato_900Black",
    secondary_bold_Italic: "Lato_700Bold_Italic",

    source_regular: "SourceCodePro_400Regular",
    source_semiBold: "SourceCodePro_600SemiBold",
    source_bold: "SourceCodePro_700Bold",
    source_Black: "SourceCodePro_900Black",
  },
  fontSizes: {
    small: RFValue(12),
    smalls: RFValue(13),
    medium: RFValue(15),
    large: RFValue(16),
    xlarge: RFValue(18),
    xxlarge: RFValue(20),
    xxxlarge: RFValue(22),
    xslarge: RFValue(24),
    xsslarge: RFValue(26),
    xssslarge: RFValue(28),
    extralarge: RFValue(50),
  },
  borderRadius: {
    small: RFValue(4),
    medium: RFValue(8),
    large: RFValue(12),
    xlarge: RFValue(16),
    xxlarge: RFValue(20),
    xxxlarge: RFValue(24),
  },
  borderWidth: {
    small: RFValue(1),
    medium: RFValue(2),
    large: RFValue(3),
    xlarge: RFValue(4),
    xxlarge: RFValue(5),
    xxxlarge: RFValue(6),
  },
  spacing: {
    small: RFValue(4),
    medium: RFValue(8),
    large: RFValue(12),
    xlarge: RFValue(16),
    xxlarge: RFValue(20),
    xxxlarge: RFValue(24),
    xslarge: RFValue(28),
    xsslarge: RFValue(32),
  },
  radius: {
    small: RFValue(4),
    medium: RFValue(8),
    large: RFValue(12),

    xlarge: RFValue(16),
    xxlarge: RFValue(20),
    xxxlarge: RFValue(24),
  },
  shadows: {
    small: "0px 8px 16px rgba(0,0,0,0.1)",
    medium: "0px 8px 16px rgba(0,0,0,0.2)",
    large: "0px 8px 16px rgba(0,0,0,0.3)",
    xlarge: "0px 8px 16px rgba(0,0,0,0.4)",
  },
  images: {
    logo: "",
  },
};
